include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    deprecated_member_use: ignore
    invalid_annotation_target: ignore
    unnecessary_null_in_if_null_operators: ignore

linter:
  rules:
