// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxWn0PFFt2b4bw93UdcLIMGQbngFJ5hg',
    appId: '1:84194566505:web:be25bae63acfe11c9f5df8',
    messagingSenderId: '84194566505',
    projectId: 'forgedance-52c54',
    authDomain: 'forgedance-52c54.firebaseapp.com',
    storageBucket: 'forgedance-52c54.firebasestorage.app',
    measurementId: 'G-SXVSHNKLFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJURmKz0HBB8Ryeb51LNhgbF-P0fX-1qw',
    appId: '1:84194566505:android:e48121a47eb1bdf49f5df8',
    messagingSenderId: '84194566505',
    projectId: 'forgedance-52c54',
    storageBucket: 'forgedance-52c54.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqpb0EpA_E9J7YwrQyP3lSog3RWrFsOME',
    appId: '1:84194566505:ios:e44d0cc9d33e239d9f5df8',
    messagingSenderId: '84194566505',
    projectId: 'forgedance-52c54',
    storageBucket: 'forgedance-52c54.firebasestorage.app',
    iosBundleId: 'dance.forge.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqpb0EpA_E9J7YwrQyP3lSog3RWrFsOME',
    appId: '1:84194566505:ios:e44d0cc9d33e239d9f5df8',
    messagingSenderId: '84194566505',
    projectId: 'forgedance-52c54',
    storageBucket: 'forgedance-52c54.firebasestorage.app',
    iosBundleId: 'dance.forge.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSxWn0PFFt2b4bw93UdcLIMGQbngFJ5hg',
    appId: '1:84194566505:web:0e3903cc52ce83ad9f5df8',
    messagingSenderId: '84194566505',
    projectId: 'forgedance-52c54',
    authDomain: 'forgedance-52c54.firebaseapp.com',
    storageBucket: 'forgedance-52c54.firebasestorage.app',
    measurementId: 'G-K4E0HHXPB5',
  );
}
