// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcEmnieB8kA9Tc2fc_CFYw30mI7FKsPg',
    appId: '1:125200254439:web:01b3303894b624e5b46942',
    messagingSenderId: '125200254439',
    projectId: 'forge-dance-1bcc7',
    authDomain: 'forge-dance-1bcc7.firebaseapp.com',
    storageBucket: 'forge-dance-1bcc7.firebasestorage.app',
    measurementId: 'G-W3L0GGCBSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbxxi1tpkI35AOsLhH9ZnIjT_QIixKtI',
    appId: '1:125200254439:android:7716c685b2698e11b46942',
    messagingSenderId: '125200254439',
    projectId: 'forge-dance-1bcc7',
    storageBucket: 'forge-dance-1bcc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWmbloURoUt6JQxC7LFrHBq_wz7rMrwS8',
    appId: '1:125200254439:ios:6fb628be883a2608b46942',
    messagingSenderId: '125200254439',
    projectId: 'forge-dance-1bcc7',
    storageBucket: 'forge-dance-1bcc7.firebasestorage.app',
    iosBundleId: 'dance.forge.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWmbloURoUt6JQxC7LFrHBq_wz7rMrwS8',
    appId: '1:125200254439:ios:6fb628be883a2608b46942',
    messagingSenderId: '125200254439',
    projectId: 'forge-dance-1bcc7',
    storageBucket: 'forge-dance-1bcc7.firebasestorage.app',
    iosBundleId: 'dance.forge.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcEmnieB8kA9Tc2fc_CFYw30mI7FKsPg',
    appId: '1:125200254439:web:9547622fe0cd3fdab46942',
    messagingSenderId: '125200254439',
    projectId: 'forge-dance-1bcc7',
    authDomain: 'forge-dance-1bcc7.firebaseapp.com',
    storageBucket: 'forge-dance-1bcc7.firebasestorage.app',
    measurementId: 'G-EL5GJE8WX9',
  );
}
