import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:widgetbook/widgetbook.dart';
import 'package:widgetbook_annotation/widgetbook_annotation.dart' as widgetbook;

import 'widgetbook.directories.g.dart';
import 'tokens/app_colors.dart';
import 'tokens/app_typography.dart';

/// Entry point for running the design system Widgetbook.
///
/// Run with:
/// `flutter run -t lib/widgetbook/main_widgetbook.dart`
///
/// After making changes to use cases, regenerate directories with:
/// `dart run build_runner build -d`
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  runApp(
    ProviderScope(
      child: EasyLocalization(
        supportedLocales: const [Locale('en'), Locale('vi')],
        path: 'assets/translations',
        fallbackLocale: const Locale('en'),
        useOnlyLangCode: true,
        child: const ForgeWidgetbook(),
      ),
    ),
  );
}

/// Root Widgetbook app configured around the Forge design system.
@widgetbook.App()
class ForgeWidgetbook extends StatelessWidget {
  const ForgeWidgetbook({super.key});

  ThemeData _darkTheme() {
    final base = ThemeData.dark();
    return base.copyWith(
      scaffoldBackgroundColor: AppColors.gray950,
      colorScheme: base.colorScheme.copyWith(
        primary: AppColors.forgeFire,
        secondary: AppColors.electricBlue,
      ),
      textTheme: base.textTheme.copyWith(
        displayLarge: AppTheme.h1,
        displayMedium: AppTheme.h2,
        titleLarge: AppTheme.h5,
        bodyLarge: AppTheme.bodyLarge,
        bodyMedium: AppTheme.body,
        bodySmall: AppTheme.bodySmall,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      addons: [
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(
              name: 'Dark',
              data: _darkTheme(),
            ),
          ],
        ),
        DeviceFrameAddon(devices: Devices.all),
        TextScaleAddon(scales: [1.0, 1.2, 1.5]),
        AlignmentAddon(),
      ],
      // This will be generated by build_runner from @UseCase annotations
      directories: directories,
    );
  }
}
